Repository teummeireo/NeverLookBack, pull requests merged in 2025-02, with the labels that each got.

#65 [feat] #62 운영자 페이지 완성
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/java/com/nlb/controller/NlbUserRestController.java
  src/main/java/com/nlb/mapper/NlbUserMapper.java
  src/main/java/com/nlb/service/NlbUserService.java
  src/main/java/com/nlb/service/NlbUserServiceImpl.java
  src/main/java/org/example/Main.java
  src/main/resources/mapper/nlbuser-mapper.xml
  src/main/webapp/css/admin.css
  src/main/webapp/jsp/admin/admin.jsp
  src/main/webapp/jsp/admin/manage_exams.jsp
  src/main/webapp/jsp/admin/manage_user.jsp
  src/main/webapp/jsp/my_page.jsp
  src/main/webapp/jsp/unregister_user.jsp
Labels: feat ✨

#67 [feat]/#43 회원가입 api 구현
  .gitignore
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/java/com/nlb/controller/NlbUserRestController.java
  src/main/java/com/nlb/mapper/NlbUserMapper.java
  src/main/java/com/nlb/service/EmailService.java
  src/main/java/com/nlb/service/EmailServiceImpl.java
  src/main/java/com/nlb/service/NlbUserService.java
  src/main/java/com/nlb/service/NlbUserServiceImpl.java
  src/main/java/com/nlb/util/EmailSenderUtil.java
  src/main/resources/google-mail-config.properties
  src/main/resources/mail-config.xml
  src/main/resources/mapper/nlbuser-mapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/root-context.xml
  src/main/webapp/WEB-INF/servlet-context.xml
  src/main/webapp/css/login_register_find.css
  src/main/webapp/css/mypage.css
  src/main/webapp/images/nlblogo.jpg
  src/main/webapp/jsp/mypage_repw.jsp
  src/main/webapp/jsp/register.jsp
Labels: feat ✨

#78 [feat] #69 프론트 백 연결
  src/main/java/com/nlb/controller/AdminRestController.java
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/resources/mapper/nlbuser-mapper.xml
  src/main/webapp/jsp/admin/manage_user.jsp
  src/main/webapp/jsp/sidebar.jsp
Labels: feat ✨

#79 [feat] #75 로그인 로그아웃 구현 완료
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/java/com/nlb/util/SessionValidationFilter.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/jsp/sidebar.jsp
Labels: feat ✨

#82 [feat] #80 exam result 로 이동하는 코드추가
  src/main/webapp/jsp/exam/my_exam.jsp
  src/main/webapp/jsp/sidebar.jsp
  src/test/java/com/nlb/controller/NlbUserRestControllerTest.java
  src/test/java/com/nlb/mapper/NlbUserMapperTest.java
  src/test/java/com/nlb/service/ExamResultServiceImplTest.java
  src/test/java/com/nlb/service/NlbUserServiceImplTest.java
Labels: feat ✨

#84 [feat] #81 new_main 페이지 구현
  src/main/webapp/css/main.css
  src/main/webapp/css/new_main.css
  src/main/webapp/grafana-test.jsp
  src/main/webapp/images/main_img.png
  src/main/webapp/images/v2-multiple-choice.677ae516.svg
  src/main/webapp/images/v2-open-text.528bda21.svg
  src/main/webapp/images/v2-quiz.3d63620f.svg
  src/main/webapp/images/v2-ranking-poll.svg
  src/main/webapp/images/v2-rating-poll.748b1a7e.svg
  src/main/webapp/images/v2-survey.79c5bdf7.svg
  src/main/webapp/images/v2-wordcloud.41258620.svg
  src/main/webapp/jsp/main.jsp
  src/main/webapp/jsp/new_main.jsp
Labels: feat ✨

#87 [feat]#76 시험생성페이지 프론트 구현&백연결
  src/main/java/com/nlb/controller/ExamController.java
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/webapp/jsp/exam/create_exam.jsp
  src/main/webapp/jsp/exam/make_exam.jsp
Labels: feat ✨

#89 Feat/#88 시험응시 프론트 백엔드 연결 1차
  src/main/java/com/nlb/controller/ExamController.java
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/dto/response/FullExamDataResDTO.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/webapp/jsp/exam/create_exam.jsp
  src/main/webapp/jsp/exam/take_exam.jsp
Labels: feat ✨, fix 💥, refactor 🧹

#90 [feat] 시험-검색필터링-API-구현
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/webapp/jsp/login_info/login.jsp
  src/main/webapp/jsp/main.jsp
  src/main/webapp/jsp/register.jsp
  src/main/webapp/jsp/search_filter.jsp
Labels: feat ✨

#93 [feat] #83 이전 응시 내역 api 연동
  src/main/resources/mapper/exam-result-mapper.xml
  src/main/webapp/css/exam_result.css
  src/main/webapp/jsp/exam/exam_result.jsp
Labels: feat ✨

#96 [feat] #95 메일 양식 꾸미기 완료
  src/main/java/com/nlb/service/EmailServiceImpl.java
  src/main/resources/mongo-config.properties
Labels: feat ✨

#97 [feat] #94 manage_user.jsp api 연동
  src/main/java/com/nlb/controller/AdminRestController.java
  src/main/java/com/nlb/mapper/NlbUserMapper.java
  src/main/java/com/nlb/service/NlbUserService.java
  src/main/java/com/nlb/service/NlbUserServiceImpl.java
  src/main/resources/mapper/nlbuser-mapper.xml
  src/main/webapp/css/manage_user.css
  src/main/webapp/jsp/admin/manage_user.jsp
Labels: feat ✨

#99 [feat] 최근 검색어-API-구현
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/SearchHistoryController.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/java/com/nlb/service/SearchHistoryService.java
  src/main/java/com/nlb/service/SearchHistoryServiceImpl.java
  src/main/java/com/nlb/vo/SearchHistoryMongoVO.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/webapp/css/main.css
  src/main/webapp/images/nlblogo.jpg
  src/main/webapp/images/nlblogo.png
  src/main/webapp/jsp/main.jsp
  src/main/webapp/jsp/recent_search.jsp
  src/main/webapp/jsp/search_filter.jsp
Labels: feat ✨

#104 [feat] #102 created_exam.jsp 페이지 생성 및 api 연동
  src/main/webapp/css/admin.css
  src/main/webapp/css/created_exam.css
  src/main/webapp/css/my_exam.css
  src/main/webapp/jsp/admin/admin.jsp
  src/main/webapp/jsp/exam/exam_creater/created_exam.jsp
  src/main/webapp/jsp/exam/exam_result.jsp
  src/main/webapp/jsp/exam/my_exam.jsp
Labels: feat ✨

#106 [feat] #103 시험 응시 코드 수정 및 제출 버튼 구현 완료
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/java/com/nlb/vo/ExamResultMongoVO.java
  src/main/webapp/grafana-test.jsp
  src/main/webapp/jsp/exam/take_exam.jsp
  src/main/webapp/jsp/my_page.jsp
Labels: feat ✨

#108 [feat] #107 회원가입, 로그인, 아이디 찾기, 운영자, 마이페이지 점검 완료
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/java/com/nlb/controller/NlbUserRestController.java
  src/main/java/com/nlb/service/NlbUserServiceImpl.java
  src/main/webapp/jsp/login_info/find_id.jsp
  src/main/webapp/jsp/login_info/find_pw.jsp
  src/main/webapp/jsp/login_info/login.jsp
  src/main/webapp/jsp/page_edit.jsp
  src/main/webapp/jsp/register.jsp
  src/main/webapp/jsp/sidebar.jsp
  src/main/webapp/jsp/unregister_user.jsp
Labels: feat ✨

#110 Feat/#92 시험응시 관련 api 전부연결
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/controller/ExamWebSocketController.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/repository/ExamRepository.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/java/com/nlb/service/WebSocketExamService.java
  src/main/java/com/nlb/service/WebSocketExamServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/resources/mapper/exam-result-mapper.xml
  src/main/webapp/WEB-INF/servlet-context.xml
  src/main/webapp/jsp/exam/make_exam.jsp
  src/main/webapp/jsp/exam/take_exam.jsp
Labels: feat ✨

#112 Feat/#109 feat 시험 생성 초기 데이터 입력 페이지 구현
  src/main/java/com/nlb/controller/ExamController.java
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/webapp/css/init_exam.css
  src/main/webapp/jsp/exam/create_exam.jsp
  src/main/webapp/jsp/exam/init_exam.jsp
  src/main/webapp/jsp/new_main.jsp
  src/main/webapp/jsp/sidebar.jsp
Labels: feat ✨

#119 [Feat]#116 feat 내 생성 시험 리스트 페이지 수정
  src/main/java/com/nlb/controller/AdminController.java
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/dto/response/FullExamDataResDTO.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/webapp/assets/fonts/Pretendard-Bold.otf
  src/main/webapp/assets/fonts/Pretendard-Bold.woff2
  src/main/webapp/assets/fonts/Pretendard-Light.woff2
  src/main/webapp/assets/fonts/Pretendard-Regular.otf
  src/main/webapp/assets/fonts/Pretendard-Regular.woff2
  src/main/webapp/css/admin.css
  src/main/webapp/css/create_exam.css
  src/main/webapp/css/created_exam.css
  src/main/webapp/css/exam_result.css
  src/main/webapp/css/init_exam.css
  src/main/webapp/css/login_register_find.css
  src/main/webapp/css/main.css
  src/main/webapp/css/manage_exam.css
  src/main/webapp/css/manage_user.css
  src/main/webapp/css/my_exam.css
  src/main/webapp/css/my_exam_detail.css
  src/main/webapp/css/my_page.css
  src/main/webapp/css/mypage.css
  src/main/webapp/css/new_main.css
  src/main/webapp/css/page_edit.css
  src/main/webapp/css/search_filter.css
  src/main/webapp/css/sidebar.css
  src/main/webapp/css/submission_check.css
  src/main/webapp/css/unregister_user.css
  src/main/webapp/jsp/admin/statistic_exams.jsp
  src/main/webapp/jsp/admin/statistic_site.jsp
  src/main/webapp/jsp/exam/create_exam.jsp
  src/main/webapp/jsp/exam/exam_creater/created_exam.jsp
  src/main/webapp/jsp/exam/exam_creater/submission_check.jsp
  src/main/webapp/jsp/logout.jsp
  src/main/webapp/jsp/register.jsp
  src/main/webapp/jsp/sidebar.jsp
Labels: feat ✨

#123 Feat/#122 feat 응시자 결과jsp 수정
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/java/com/nlb/dto/response/ExamResultDTO.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/resources/mapper/exam-result-mapper.xml
  src/main/webapp/css/submission_check.css
  src/main/webapp/jsp/exam/exam_creater/submission_check.jsp
  src/main/webapp/jsp/exam/my_exam.jsp
  src/main/webapp/jsp/exam/my_exam_detail.jsp
  src/main/webapp/jsp/sidebar.jsp
Labels: feat ✨

#126 [mod/#124-mod-병합-후-충돌-해결
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/resources/mybatis-config.xml
Labels: mod 〰

#132 [mod]/#130-mod-병합-후-충돌-해결3
  src/main/webapp/jsp/exam_search.jsp
  src/main/webapp/jsp/search_filter.jsp
Labels: mod 〰

#133 [feat]#111-MY_RESULT_DETAIL 댓글달기
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/dto/response/FullExamDataResDTO.java
  src/main/webapp/jsp/exam/my_exam_detail.jsp
Labels: feat ✨

#137 [feat]#128 css 수정
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/webapp/css/created_exam.css
  src/main/webapp/css/exam_result.css
  src/main/webapp/css/login_register_find.css
  src/main/webapp/css/my_exam.css
  src/main/webapp/jsp/admin/statistic_site.jsp
  src/main/webapp/jsp/exam/exam_creater/created_exam.jsp
  src/main/webapp/jsp/exam/exam_creater/submission_check.jsp
  src/main/webapp/jsp/exam_search.jsp
  src/main/webapp/jsp/login_info/find_pw.jsp
  src/main/webapp/jsp/new_main.jsp
Labels: feat ✨

#139 feat/#135 created exam page 작성
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/webapp/jsp/exam/exam_creater/created_exam_detail.jsp
  src/main/webapp/jsp/exam/my_exam_detail.jsp
Labels: feat ✨

#142 [feat]#140-detail 페이지들 연결-점검
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/webapp/jsp/exam/exam_result.jsp
Labels: refactor 🧹

#146 [ui]/#145-ui-검색-목록-ui-수정2
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/dto/response/RecentScoreDTO.java
  src/main/java/com/nlb/dto/response/VisitorStatsDTO.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/webapp/css/exam_result.css
  src/main/webapp/css/exam_search.css
  src/main/webapp/jsp/exam_search.jsp
Labels: ui 🎨

#148 [UI] #141 css 부분 수정
  src/main/webapp/css/exam_search.css
  src/main/webapp/css/init_exam.css
  src/main/webapp/css/my_exam.css
  src/main/webapp/css/my_exam_detail.css
  src/main/webapp/jsp/exam/init_exam.jsp
  src/main/webapp/jsp/exam/my_exam.jsp
  src/main/webapp/jsp/exam/my_exam_detail.jsp
  src/main/webapp/jsp/exam_search.jsp
  src/main/webapp/jsp/sidebar.jsp
Labels: ui 🎨

#150 [ui] #149 css 부분 수정
  src/main/webapp/css/exam_search.css
Labels: ui 🎨

#151 [ui]/#147-ui-이전-응시-내역-ui-수정
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/dto/response/ExamMyResultCardDTO.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/resources/mapper/exam-result-mapper.xml
  src/main/webapp/jsp/exam/exam_result.jsp
Labels: ui 🎨

#159 [feat] #153 시나리오 테스트완료
  src/main/webapp/jsp/admin/statistic_exams.jsp
  src/main/webapp/jsp/exam/exam_creater/created_exam_detail.jsp
  src/main/webapp/jsp/exam/exam_result.jsp
  src/main/webapp/jsp/exam/my_exam_detail.jsp
Labels: feat ✨

#160 [mod] #157 시험 응시 페이지 내부 수정
  src/main/webapp/css/create_exam.css
  src/main/webapp/jsp/exam/create_exam.jsp
Labels: mod 〰
