Repository teummeireo/NeverLookBack, pull requests merged in 2025-01, with the labels that each got.

#4 [feat] # 2 그라파나 테스트 완료
  pom.xml
  src/main/java/com/nlb/controller/HomeController.java
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/grafana-test.jsp
Labels: feat ✨

#5 [feat] #2 db 간 연ehd
  .gitignore
  src/main/java/com/nlb/controller/HomeController.java
  src/main/webapp/WEB-INF/servlet-context.xml
Labels: feat ✨

#8 [feat] #6 초기 구조 및 단위 테스트 샘플 코드 작성 완료
  pom.xml
  src/main/java/com/nlb/controller/ExamController.java
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/controller/HomeController.java
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/java/com/nlb/controller/NlbUserRestController.java
  src/main/java/com/nlb/dto/response/MsgResDTO.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/mapper/HomeMapper.java
  src/main/java/com/nlb/mapper/NlbUserMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/java/com/nlb/service/HomeService.java
  src/main/java/com/nlb/service/NlbUserService.java
  src/main/java/com/nlb/service/NlbUserServiceImpl.java
  src/main/java/com/nlb/vo/ExamResultVO.java
  src/main/java/com/nlb/vo/ExamVO.java
  src/main/java/com/nlb/vo/HomeVO.java
  src/main/java/com/nlb/vo/NlbUserVO.java
  src/main/java/com/nlb/vo/ResultDetailVO.java
  src/main/resources/mapper/nlbuser-mapper.xml
  src/test/java/com/nlb/controller/NlbUserRestControllerTest.java
  src/test/java/com/nlb/mapper/NlbUserMapperTest.java
  src/test/java/com/nlb/service/NlbUserServiceImplTest.java
Labels: feat ✨

#18 [feat] #17 VO 추가 완료
  .gitignore
  src/main/java/com/nlb/vo/ExamMongoVO.java
  src/main/java/com/nlb/vo/ExamResultMongoVO.java
Labels: feat ✨

#20 Add/#13 page_edit.jsp 구현
  out/artifacts/users_war_exploded/css/login_register_find.css
  out/artifacts/users_war_exploded/css/my_page.css
  out/artifacts/users_war_exploded/css/unregister_user.css
  out/artifacts/users_war_exploded/jsp/login_info/find_id.jsp
  out/artifacts/users_war_exploded/jsp/login_info/login.jsp
  out/artifacts/users_war_exploded/jsp/main.jsp
  out/artifacts/users_war_exploded/jsp/my_page.jsp
  out/artifacts/users_war_exploded/jsp/register.jsp
  src/main/webapp/css/login_register_find.css
  src/main/webapp/css/my_page.css
  src/main/webapp/css/page_edit.css
  src/main/webapp/css/unregister_user.css
  src/main/webapp/jsp/login_info/find_id.jsp
  src/main/webapp/jsp/login_info/login.jsp
  src/main/webapp/jsp/main.jsp
  src/main/webapp/jsp/my_page.jsp
  src/main/webapp/jsp/page_edit.jsp
  src/main/webapp/jsp/register.jsp
Labels: add ➕

#26 [feat] #25 응시 결과 리스트 확인 페이지 api 구현 완료
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/resources/mapper/exam-result-mapper.xml
Labels: feat ✨

#28 [feat]#27-feat-이전 응시내역 페이지 밑작업
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/org/example/Main.java
  src/main/webapp/css/my_exam.css
  src/main/webapp/jsp/exam/my_exam.jsp
Labels: feat ✨

#31 [feat] #30 나의 응시한 시험 페이지 api 구현 완료
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/dto/response/ExamResultCardDTO.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/resources/mapper/exam-result-mapper.xml
  src/main/resources/mybatis-config.xml
  src/test/java/com/nlb/controller/ExamRestControllerTest.java
  src/test/java/com/nlb/controller/ExamResultRestControllerTest.java
  src/test/java/com/nlb/mapper/ExamResultMapperTest.java
  src/test/java/com/nlb/service/ExamResultServiceImplTest.java
Labels: feat ✨

#33 [feat] #32 운영자 페이지 API 구현 완료
  src/main/java/com/nlb/controller/AdminRestController.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/mapper/NlbUserMapper.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/java/com/nlb/service/NlbUserService.java
  src/main/java/com/nlb/service/NlbUserServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/resources/mapper/nlbuser-mapper.xml
Labels: feat ✨

#35 [feat] #34 마이페이지 api 구현 구현 완료
  src/main/java/com/nlb/controller/NlbUserRestController.java
  src/main/java/com/nlb/mapper/NlbUserMapper.java
  src/main/java/com/nlb/service/NlbUserService.java
  src/main/java/com/nlb/service/NlbUserServiceImpl.java
  src/main/java/com/nlb/util/PasswordUtil.java
  src/main/resources/mapper/nlbuser-mapper.xml
  src/test/java/com/nlb/controller/NlbUserRestControllerTest.java
  src/test/java/com/nlb/mapper/NlbUserMapperTest.java
  src/test/java/com/nlb/service/NlbUserServiceImplTest.java
Labels: feat ✨

#36 [feat] #24 시험/문제지 생성 관련 API 1차 구현
  src/main/java/com/nlb/controller/ExamController.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/repository/ExamRepository.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/java/com/nlb/vo/ExamMongoVO.java
  src/main/java/com/nlb/vo/ExamVO.java
  src/main/java/com/nlb/vo/QuestionVO.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/webapp/WEB-INF/servlet-context.xml
Labels: feat ✨

#41 [feat] #40 add 마이페이지 관련 api 연결
  classes/artifacts/kosta_server/WEB-INF/classes/mapper/exam-mapper.xml
  classes/artifacts/kosta_server/WEB-INF/classes/mapper/exam-result-mapper.xml
  classes/artifacts/kosta_server/WEB-INF/classes/mapper/nlbuser-mapper.xml
  classes/artifacts/kosta_server/WEB-INF/classes/mybatis-config.xml
  classes/artifacts/kosta_server/WEB-INF/servlet-context.xml
  classes/artifacts/kosta_server/css/main.css
  classes/artifacts/kosta_server/css/my_page.css
  classes/artifacts/kosta_server/css/page_edit.css
  classes/artifacts/kosta_server/jsp/exam/exam_result.jsp
  classes/artifacts/kosta_server/jsp/exam/my_exam.jsp
  classes/artifacts/kosta_server/jsp/main.jsp
  classes/artifacts/kosta_server/jsp/my_page.jsp
  classes/artifacts/kosta_server/jsp/page_edit.jsp
  classes/artifacts/kosta_server/jsp/sidebar.jsp
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/webapp/css/main.css
  src/main/webapp/css/my_page.css
  src/main/webapp/css/page_edit.css
  src/main/webapp/jsp/exam/exam_result.jsp
  src/main/webapp/jsp/exam/my_exam.jsp
  src/main/webapp/jsp/login_info/login.jsp
  src/main/webapp/jsp/main.jsp
  src/main/webapp/jsp/my_page.jsp
  src/main/webapp/jsp/page_edit.jsp
  src/main/webapp/jsp/sidebar.jsp
  src/test/java/com/nlb/controller/ExamRestControllerTest.java
  src/test/java/com/nlb/service/ExamServiceImplTest.java
Labels: feat ✨

#47 [feat] #46 분산 트랜잭션 aop 적용 완료
  src/main/java/com/nlb/aop/DistributedTransactionAspect.java
  src/main/java/com/nlb/vo/ExamVO.java
  src/main/webapp/WEB-INF/servlet-context.xml
  src/test/java/com/nlb/controller/ExamRestControllerTest.java
  src/test/java/com/nlb/service/ExamServiceImplTest.java
Labels: feat ✨

#48 Feat/#45 시험 제출 자동 채점 및 내 시험답안, 응시자 정보 표기 API 개발
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/dto/response/ExamResultCardDTO.java
  src/main/java/com/nlb/dto/response/ExamineeInfoResDTO.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/resources/mapper/exam-result-mapper.xml
Labels: feat ✨

#50 Feat/#49 응시자 답안상세관련 api들
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/dto/response/CMResDTO.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/resources/mapper/exam-result-mapper.xml
Labels: feat ✨

#53 [feat] #42 응시자 결과 확인 페이지.jsp 밑작업
  classes/artifacts/kosta_server/WEB-INF/classes/mapper/exam-result-mapper.xml
  classes/artifacts/kosta_server/css/submission_check.css
  classes/artifacts/kosta_server/jsp/exam/exam_creater/submission_check.jsp
  classes/artifacts/kosta_server/jsp/login_info/login.jsp
  classes/artifacts/kosta_server/jsp/sidebar.jsp
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/java/com/nlb/vo/ExamResultMongoVO.java
  src/main/resources/mapper/exam-result-mapper.xml
  src/main/webapp/css/submission_check.css
  src/main/webapp/jsp/exam/exam_creater/submission_check.jsp
  src/main/webapp/jsp/sidebar.jsp
Labels: feat ✨

#54 [feat] #52 main , my_page, page_edit 매핑 완료
  src/main/java/com/nlb/controller/NlbUserController.java
  src/main/java/com/nlb/controller/NlbUserRestController.java
  src/main/java/com/nlb/vo/ExamVO.java
  src/main/webapp/grafana-test.jsp
  src/main/webapp/jsp/my_page.jsp
  src/main/webapp/jsp/page_edit.jsp
  src/main/webapp/jsp/sidebar.jsp
Labels: feat ✨

#57 [fix] #56 병합 충돌 해결
  classes/artifacts/kosta_server/WEB-INF/classes/mapper/exam-mapper.xml
  classes/artifacts/kosta_server/WEB-INF/classes/mapper/exam-result-mapper.xml
  classes/artifacts/kosta_server/WEB-INF/servlet-context.xml
  classes/artifacts/kosta_server/grafana-test.jsp
  classes/artifacts/kosta_server/jsp/exam/exam_creater/submission_check.jsp
  classes/artifacts/kosta_server/jsp/my_page.jsp
  classes/artifacts/kosta_server/jsp/page_edit.jsp
  classes/artifacts/kosta_server/jsp/sidebar.jsp
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
Labels: fix 💥

#59 [mod] sidebar.css 변경
  classes/artifacts/kosta_server/css/main.css
  classes/artifacts/kosta_server/css/sidebar.css
  classes/artifacts/kosta_server/jsp/main.jsp
  classes/artifacts/kosta_server/jsp/sidebar.jsp
  src/main/webapp/css/main.css
  src/main/webapp/css/sidebar.css
  src/main/webapp/jsp/main.jsp
  src/main/webapp/jsp/sidebar.jsp
Labels: mod 〰

#55 Feat/#51 채점관련 api 개발 및 오류 수정
  src/main/java/com/nlb/controller/ExamRestController.java
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/dto/request/ScoreUpdateReqDTO.java
  src/main/java/com/nlb/exception/ErrorCode.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
  src/main/java/com/nlb/service/ExamService.java
  src/main/java/com/nlb/service/ExamServiceImpl.java
  src/main/resources/mapper/exam-mapper.xml
  src/main/resources/mapper/exam-result-mapper.xml
Labels: feat ✨, fix 💥

#64 [fix]#63-API동작완료점검-노션-포스트맨-매칭 + 머지 오류 수정 및 코드 정리
  src/main/java/com/nlb/controller/ExamResultRestController.java
  src/main/java/com/nlb/mapper/ExamMapper.java
  src/main/java/com/nlb/mapper/ExamResultMapper.java
  src/main/java/com/nlb/service/ExamResultService.java
  src/main/java/com/nlb/service/ExamResultServiceImpl.java
Labels: fix 💥, refactor 🧹
